# Analysera filmrecensioner

In [1]:
import pandas as pd
import numpy as np
import src.preprocessing as prep
import src.log_reg as lr
import src.evaluation as eval
import src.distilbert_model as dbm

# Exploratory Data Analysis

In [7]:
train_df, test_df = prep.load_imdb_data_as_dataframe()

In [ ]:
train_df.info()

In [ ]:
train_df["label"].value_counts()

In [ ]:
pd.set_option('display.max_colwidth', None)
train_df.head()

In [ ]:
# Antal ord per recension
train_df["word_count"] = train_df["text"].str.split().str.len()

train_df["word_count"].describe()

In [ ]:
import re

rating_pattern = r"\b(10|[1-9])\s*(/|out of)\s*10\b"

train_ratings = train_df[
    train_df["text"].str.contains(rating_pattern, case=False, regex=True, na=False)
]

print("Antal recensioner med uttryckligt betyg:", len(train_ratings))

In [ ]:
print("POSITIVA:")
for text in train_ratings[train_ratings["label"] == 1]["text"].head(3):
    print(text)
    print("\n" + "-"*80 + "\n")

print("NEGATIVA:")
for text in train_ratings[train_ratings["label"] == 0]["text"].head(3):
    print(text)
    print("\n" + "-"*80 + "\n")

In [ ]:
common_text = set(train_df["text"]) & set(test_df["text"])
print("Reviews in both train and test sets:", len(common_text))

# Logistic Regression

In [8]:
X_train, X_val, X_test, y_train, y_val, y_test = prep.prepare_data_for_logreg(train_df, test_df)
tfidf, X_train_tfidf, X_val_tfidf, X_test_tfidf = lr.vectorize_text(X_train, X_val, X_test)

model = lr.train_logistic_regression(X_train_tfidf, y_train)
y_val_pred = model.predict(X_val_tfidf)
y_val_proba = model.predict_proba(X_val_tfidf)

In [9]:
val_results_lr = eval.calculate_metrics(y_val, y_val_pred)
print("Validation results:")
for metric, value in val_results_lr.items():
  print(f"{metric.capitalize()}: {value:.4f}")

Validation results:
Accuracy: 0.8854
Precision: 0.8770
Recall: 0.8950
F1: 0.8859

In [ ]:
confusion_matrix_lr = eval.create_confusion_matrix(y_val, y_val_pred)

In [ ]:
classification_report = eval.classification_report(y_val, y_val_pred)
print(classification_report)

In [ ]:
prediction_errors = eval.get_prediction_errors(y_val, y_val_pred, X_val, y_val_proba)

display(prediction_errors.head(8))

### Logistic Regression: utvärdering på testdata

In [11]:
# Predict on test data
y_test_pred = model.predict(X_test_tfidf)
y_test_proba = model.predict_proba(X_test_tfidf)

# Evaluate test results
test_results_lr = eval.calculate_metrics(y_test, y_test_pred)

print("Test results:")
for metric, value in test_results_lr.items():
    print(f"{metric.capitalize()}: {value:.4f}")

Test results:
Accuracy: 0.8809
Precision: 0.8797
Recall: 0.8833
F1: 0.8815

In [ ]:
confusion_matrix_lr_test = eval.create_confusion_matrix(y_test, y_test_pred)

In [ ]:
classification_report_test = eval.classification_report(y_test, y_test_pred)
print(classification_report_test)

In [ ]:
prediction_errors_test = eval.get_prediction_errors(y_test, y_test_pred, X_test, y_test_proba)

display(prediction_errors_test.head(8))

# DistilBERT

In [2]:
train_dataset, val_dataset, test_dataset = prep.prepare_data_for_distilbert()

sampled_split = train_dataset.train_test_split(
    train_size=5000, seed=42, stratify_by_column="label"
)
small_train_dataset = sampled_split["train"]

tokenized_train, tokenized_val, tokenized_test, tokenizer = dbm.tokenize_datasets(small_train_dataset, val_dataset, test_dataset)

model, data_collator = dbm.get_model_and_collator(tokenizer)

trainer = dbm.setup_trainer(model, tokenized_train, tokenized_val, data_collator)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [3]:
trainer.train()

c:\Users\nadin\Documents\projekt_ds\.venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

TrainOutput(global_step=157, training_loss=0.37261349380395975, metrics={'train_runtime': 8762.9341, 'train_samples_per_second': 0.571, 'train_steps_per_second': 0.018, 'total_flos': 661881636597120.0, 'train_loss': 0.37261349380395975, 'epoch': 1.0})

### DistilBERT: utvärdering på testdata

In [4]:
test_results = trainer.predict(tokenized_test)

y_true_db = test_results.label_ids
y_pred_db = np.argmax(test_results.predictions, axis=1)

test_metrics = eval.calculate_metrics(y_true_db, y_pred_db)
print("Test Metrics for DistilBERT:")
for metric, value in test_metrics.items():
  print(f"{metric.capitalize()}: {value:.4f}")

c:\Users\nadin\Documents\projekt_ds\.venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Test Metrics for DistilBERT:
Accuracy: 0.8971
Precision: 0.8955
Recall: 0.8996
F1: 0.8976

In [ ]:
eval.create_confusion_matrix(y_true_db, y_pred_db, title="DistilBERT Confusion Matrix")

In [ ]:
from scipy.special import softmax

y_proba_db = softmax(test_results.predictions, axis=1)

errors_db = eval.get_prediction_errors(
    y_true_db, y_pred_db, test_dataset["text"], y_proba_db
)
display(errors_db.head(8))

## Jämförelse Logistic Regression och DistilBERT

In [12]:
comparison = pd.DataFrame({
    "Logistic Regression": test_results_lr,
    "DistilBERT": test_metrics
})

display(comparison.round(4))

           Logistic Regression  DistilBERT
accuracy                0.8809      0.8971
precision               0.8797      0.8955
recall                  0.8833      0.8996
f1                      0.8815      0.8976

Resultaten visar att båda modellerna presterade bra vid sentimentanalys av IMDb-recensioner. Logistic Regression uppnådde en accuracy på 88,09 % på testdata, medan DistilBERT uppnådde 89,71 %. DistilBERT hade även högre precision, recall och F1-score.

Skillnaden mellan modellerna var relativt liten, men resultaten visar att DistilBERT presterade bättre på samtliga utvärderingsmått. Detta kan bero på att DistilBERT använder förtränade språkliga representationer som kan fånga sammanhang i texten, medan Logistic Regression med TF-IDF främst utgår från ordens förekomst och viktning.

En viktig skillnad mellan experimenten var mängden träningsdata. Logistic Regression tränades på 20 000 recensioner, medan DistilBERT tränades på 5 000 recensioner. Vi begränsade träningsmängden för DistilBERT eftersom träningen krävde betydligt mer beräkningstid och resurser.

Trots att DistilBERT tränades på en fjärdedel så många recensioner presterade modellen något bättre på testdatan. Det är möjligt att DistilBERT skulle kunna uppnå ännu bättre resultat med mer träningsdata, men detta kan inte fastställas utan ytterligare experiment. Samtidigt skulle Logistic Regression också kunna prestera bättre genom hyperparameteroptimering, vilket inte genomfördes i detta projekt.

Jämförelsen visar att Logistic Regression är en effektiv baseline med god prestanda och låg beräkningskostnad, medan DistilBERT gav något bättre resultat trots den mindre träningsmängden. Resultaten bör dock tolkas med hänsyn till att modellerna tränades på olika stora datamängder och att DistilBERTs fulla potential därför inte undersöktes.

Sammantaget visar jämförelsen att DistilBERT gav bäst resultat, men att förbättringen behöver vägas mot modellens högre resursbehov.